url: http://www.whoisnicoleharris.com
timezone: Europe/London
permalink: /:year/:month/:day/:title.html
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
    sass_dir: /assets/css/_sass
    style: :compressed

collections:
    projects:
        output: true
        permalink: /:path/

exclude: [vendor]

gems:
  - jekyll-sitemap
